//! Deterministic, network-free provider for tests and L1 baselines.
//!
//! It exercises the *real* loop (parse → apply → gate) without an LLM: it reads
//! the `WRITABLE:` markers the context builder emits and returns a single
//! `<<<WRITE …>>>` action targeting the first writable path. Output is a pure
//! function of the prompt, so golden-task runs are reproducible.

use super::{ChatRequest, ChatResponse, Provider};
use crate::config::agent::ProviderSelection;
use crate::error::Result;
use crate::util::estimate_tokens;
use async_trait::async_trait;

pub struct Offline {
    model: String,
}

impl Offline {
    pub fn new(sel: &ProviderSelection) -> Self {
        Self { model: sel.model.clone() }
    }

    /// Pull the first `- <path>` line under a `WRITABLE:` header.
    fn first_writable(prompt: &str) -> Option<String> {
        let mut in_section = false;
        for line in prompt.lines() {
            let t = line.trim();
            if t.starts_with("WRITABLE:") {
                in_section = true;
                continue;
            }
            if in_section {
                if let Some(rest) = t.strip_prefix("- ") {
                    return Some(rest.trim().to_string());
                }
                if t.is_empty() {
                    continue;
                }
                break;
            }
        }
        None
    }
}

#[async_trait]
impl Provider for Offline {
    fn id(&self) -> &str {
        "offline"
    }

    async fn chat(&self, req: ChatRequest) -> Result<ChatResponse> {
        let prompt: String =
            req.messages.iter().map(|m| m.content.as_str()).collect::<Vec<_>>().join("\n");

        let content = match Self::first_writable(&prompt) {
            Some(path) => format!(
                "<<<WRITE {path}\n// generated by the orvena offline provider ({})\n>>>",
                self.model
            ),
            None => "no writable target in scope; reporting blocker".to_string(),
        };

        let input_tokens = req.messages.iter().map(|m| estimate_tokens(&m.content)).sum();
        let output_tokens = estimate_tokens(&content);
        Ok(ChatResponse { content, input_tokens, output_tokens })
    }
}
